env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
  - 'plugin:tailwindcss/recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
  - 'tailwindcss'
ignorePatterns: ['*.config.js']
rules:
  {
    'tailwindcss/classnames-order': 'warn',
    'tailwindcss/enforces-shorthand': 'warn',
    'tailwindcss/migration-from-tailwind-2': 'warn',
    'tailwindcss/no-arbitrary-value': 'off',
    'tailwindcss/no-custom-classname': 'warn',
    'tailwindcss/no-contradicting-classname': 'error',
    'vue/singleline-html-element-content-newline':
      ['error', { 'ignores': ['div', 'pre', 'textarea', ...INLINE_ELEMENTS] }],
    'vue/max-attributes-per-line': 'off',
    'vue/html-self-closing': ['error', { 'html': { 'void': 'always' } }],
  }
